import type { AIConversationTree, BusinessCategory } from '../types/ai.types';

export const APPROVED_AI_KNOWLEDGE_TREES: Record<BusinessCategory, AIConversationTree> = {
  'pitru-moksha-gaya': {
    categoryId: 'pitru-moksha-gaya',
    title: 'PitruMoksha Gaya Ritual AI',
    greeting: 'Namaste! I am your Gaya Ji ancestral ritual assistant. Select a topic or question to get verified guidance.',
    initialPrompts: [
      {
        id: 'pmg_shraddh',
        label: 'What is Shraddh and why is it performed?',
        response: 'Shraddh is a sacred Vaidik ritual performed to offer gratitude, prayers, and spiritual nourishment to departed ancestors, ensuring their eternal peace and liberation (Moksha).',
        suggestedService: 'Pitra Aatma Shanti Puja',
      },
      {
        id: 'pmg_pind_daan',
        label: 'What is Pind Daan in Gaya Ji?',
        response: 'Pind Daan is the offering of sacred rice/barley balls (Pindas) to ancestors at consecrated sites in Gaya Ji, traditionally liberating 21 generations of lineage.',
        suggestedService: 'Gaya Ji Pind Daan Seva',
      },
      {
        id: 'pmg_tarpan',
        label: 'How is Tarpan performed?',
        response: 'Tarpan is the offering of water infused with sesame seeds (Til) and Kusha grass to satisfy ancestral spirits, performed with precise Vaidik mantras.',
        suggestedService: 'Virtual Shraddh & Tarpan',
      },
      {
        id: 'pmg_gaya_rituals',
        label: 'What are the main Gaya Ji ritual sites?',
        response: 'The complete Gaya Ji yatra includes ritual offerings at Phalgu River, Vishnupad Temple, and the immortal Akshayavat tree under traditional Panda guidance.',
        suggestedService: 'Complete Gaya Pilgrimage Package',
      },
      {
        id: 'pmg_differences',
        label: 'What is the difference between Shraddh, Pind Daan & Tarpan?',
        response: 'Tarpan is the daily or tithi water offering; Shraddh is the complete formal ceremony with Brahmins; Pind Daan is the definitive ancestral liberation rite conducted at Gaya Ji.',
        suggestedService: 'Pitra Dosh Shanti',
      },
      {
        id: 'pmg_dates',
        label: 'What are the most suitable dates for Pind Daan?',
        response: 'Pitru Paksha, Amavasya tithis, and Solar/Lunar eclipses are most auspicious. However, Gaya Ji is a permanent Siddha Kshetra where rites can be performed year-round.',
        suggestedService: 'PitruMoksha Gaya Ritual Seva',
      },
      {
        id: 'pmg_pitru_paksha',
        label: 'Why is Pitru Paksha so significant in Gaya Ji?',
        response: 'Pitru Paksha (16 days of Mahalaya) is the sacred period when ancestral spirits come closest to the earthly plane to receive offerings and grant lineage blessings.',
        suggestedService: 'Pitru Paksha Bespoke Seva',
      },
      {
        id: 'pmg_gotra',
        label: 'Why is Gotra essential for ancestral rituals?',
        response: 'Gotra identifies your paternal lineage. During Sankalp, your Gotra and ancestral names are chanted so the fruits of the ritual reach your exact forefathers.',
        suggestedService: 'Vahi Lineage Verification',
      },
      {
        id: 'pmg_who_perform',
        label: 'Who is eligible to perform Pind Daan?',
        response: 'Eldest or any son traditionally performs Pind Daan. Daughters, wives, brothers, or designated proxy representatives may also perform rites according to Vaidik Shastras.',
        suggestedService: 'Proxy Ritual Assistance',
      },
      {
        id: 'pmg_nri_remote',
        label: 'How does NRI Remote Participation work?',
        response: 'NRIs join live via high-definition video link while qualified Gaya Pandas chant Sankalp with your family names and Gotra, performing all physical offerings in person.',
        suggestedService: 'Live Ritual Participation',
        requiresLeadCollection: true,
      },
      {
        id: 'pmg_offline',
        label: 'How to plan Offline In-Person Participation?',
        response: 'Our team coordinates your complete itinerary: local station/airport pickup, hotel stay, priest assignment, ritual samagri, and temple escort support.',
        suggestedService: 'Family & Elder Safety Support',
        requiresLeadCollection: true,
      },
      {
        id: 'pmg_prep',
        label: 'What preparation is required before the ritual?',
        response: 'Maintain a sattvik diet, gather your Gotra and ancestor details, keep clean traditional clothes ready, and review the Sankalp timing with your coordinator.',
        suggestedService: 'Pre-Ritual Consultation',
      },
      {
        id: 'pmg_documents',
        label: 'What documentation is provided after completion?',
        response: 'You receive an official Digital Completion Certificate, video/photo documentation, Prasad dispatch tracking, and traditional Vahi ledger registration confirmation.',
        suggestedService: 'Completion Documentation',
      },
      {
        id: 'pmg_booking',
        label: 'How do I book a ritual or consultation?',
        response: 'Submit your preferred date, family details, and participation mode. An expert coordinator verifies priest availability and confirms your schedule.',
        suggestedService: 'Platinum (Bespoke) Services',
        requiresLeadCollection: true,
      },
      {
        id: 'pmg_travel',
        label: 'What travel coordination is available for elders?',
        response: 'We provide wheelchair support, elder-friendly transport, AC accommodations near Vishnupad Temple, and dedicated ground escorts throughout the yatra.',
        suggestedService: 'Family & Elder Safety Support',
      },
      {
        id: 'pmg_stay_duration',
        label: 'How many days should I stay in Gaya Ji?',
        response: 'A typical Gaya Ji Pind Daan yatra takes 1 to 3 days depending on whether single-site (Vishnupad) or complete 3-site (Phalgu River, Vishnupad Temple, Akshayavat) rites are performed. We recommend a 2-day stay for relaxed completion.',
        suggestedService: 'Gaya Ji Yatra Itinerary',
      },
      {
        id: 'pmg_docs_required',
        label: 'What documents are required for Gaya Ji rites?',
        response: 'Carry valid photo ID (Aadhaar, Passport, or Voter ID) for temple/hotel check-in, along with your ancestral Gotra, family tree details, and past Vahi reference numbers if available.',
        suggestedService: 'Pilgrimage Document Checklist',
      },
      {
        id: 'pmg_delay_handle',
        label: 'What happens if my train or flight is delayed?',
        response: 'Our local ground coordination team tracks your train/flight status live. Your assigned escort and Panda reschedule the ritual muhurat flexibly without any penalty or lost slot.',
        suggestedService: 'Flexible Yatra Coordination',
      },
      {
        id: 'pmg_schedule_coord',
        label: 'How is the ritual schedule coordinated?',
        response: 'Upon booking, an Operations Escort is assigned to your family via WhatsApp/phone. They manage station pickup, hotel check-in, Pandit coordination, and temple timing step-by-step.',
        suggestedService: 'Dedicated Escort Coordination',
      },
      {
        id: 'pmg_women_participate',
        label: 'Can women or daughters participate in Pind Daan?',
        response: 'Yes. Vaidik Shastras permit daughters, wives, and female family members to participate in Sankalp, offer Pind Daan, or assist in ancestral prayers.',
        suggestedService: 'Family Participation Guidance',
      },
      {
        id: 'pmg_after_completion',
        label: 'What happens after ritual completion?',
        response: 'Upon ritual completion, your family receives Brahmin Dakshina confirmation, traditional Vahi ledger entry update, Prasad blessing pack dispatch, and digital documentation.',
        suggestedService: 'Post-Ritual Services',
      },
      {
        id: 'pmg_receive_docs',
        label: 'How will I receive completion documentation?',
        response: 'Digital completion certificates, high-resolution ritual photos/videos (if opted), and tracking numbers for Prasad delivery are sent directly to your WhatsApp and email.',
        suggestedService: 'Completion Documentation',
      },
      {
        id: 'pmg_prasad',
        label: 'How is Prasad dispatched to our home?',
        response: 'Consecrated Prasad, sacred Phalgu soil, and Akshayavat leaves are carefully packed and dispatched to your home address worldwide with tracking details.',
        suggestedService: 'Prasad Dispatch',
      },
    ],
    fallbackResponse: 'I will refer your specific Gaya Ji ancestral query to an authorized coordinator for human verification.',
  },
  'ritual-services': {
    categoryId: 'ritual-services',
    title: 'Vaidik Ritual & Puja AI',
    greeting: 'Namaste! Ask me about authentic home pujas, Havan, Griha Pravesh, Dosh Shanti, or custom Vaidik ceremonies.',
    initialPrompts: [
      {
        id: 'rit_selection',
        label: 'How do I select the right Vaidik ritual for my family?',
        response: 'Rituals are selected based on your Nakshatra, Gotra, specific life milestones, or family intentions. Our qualified Acharyas guide you to the prescribed ceremony.',
        suggestedService: 'Vaidik Ritual Consultation',
      },
      {
        id: 'rit_purpose',
        label: 'What is the spiritual purpose of specific pujas?',
        response: 'Pujas remove negative influences, align planetary energies (Grah Shanti), invite prosperity (Lakshmi Puja), protect health (Mahamrityunjay), or honor ancestors.',
        suggestedService: 'Puja Purpose Guidance',
      },
      {
        id: 'rit_online',
        label: 'How do Online Virtual Ritual Services work?',
        response: 'Online rituals are streamed live in high quality. Qualified Pandits recite Sankalp taking your family name, Gotra, and wish, performing all Samagri offerings on video.',
        suggestedService: 'Virtual Live-Stream Puja',
      },
      {
        id: 'rit_offline',
        label: 'How are Offline In-Person Ritual Services organized?',
        response: 'Verified Pandits visit your home, venue, or preferred pilgrimage temple with 100% authentic samagri, managing end-to-end Mandap preparation and ritual execution.',
        suggestedService: 'In-Person Pandit Booking',
        requiresLeadCollection: true,
      },
      {
        id: 'rit_customized',
        label: 'Can I request a Customized Bespoke Puja?',
        response: 'Yes! Custom Havans, multi-day Japams, specialized Anushthans, or combined ancestral-deity rites can be tailored specifically to your family requirement.',
        suggestedService: 'Customized Puja Seva',
        requiresLeadCollection: true,
      },
      {
        id: 'rit_location',
        label: 'Can rituals be conducted at my Preferred Location?',
        response: 'We arrange Pandits and sacred Samagri across major cities, towns, and designated pilgrimage teerth Kshetras according to your preferred location and time.',
        suggestedService: 'Preferred Location Booking',
      },
      {
        id: 'rit_dosh_prep',
        label: 'What is Dosh Shanti and how to prepare?',
        response: 'Dosh Shanti (Pitra Dosh, Kaal Sarp, Kalsarp, Mangal Dosh) mitigates karmic obstacles. Preparation involves fasts, sattvik diet, and providing Gotra/birth details.',
        suggestedService: 'Dosh Shanti Puja',
      },
      {
        id: 'rit_booking',
        label: 'How do I book a Pandit Ji or ritual slot?',
        response: 'Choose your desired ritual, select date and language preference, and submit your contact details. An expert coordinator verifies Pandit availability immediately.',
        suggestedService: 'Verified Pandit Booking',
        requiresLeadCollection: true,
      },
    ],
    fallbackResponse: 'I do not have an approved answer for this custom ritual requirement. I will refer your request to the authorized team.',
  },
  'travel-assistance': {
    categoryId: 'travel-assistance',
    title: 'Sacred Pilgrimage Travel AI',
    greeting: 'Namaste! Need assistance with arrival pickup, elder care, hotel stay, ghat assistance, or local escort support for your pilgrimage?',
    initialPrompts: [
      {
        id: 'trv_arrival',
        label: 'What Arrival Assistance services are provided?',
        response: 'Dedicated escorts meet you directly at Gaya Junction, Patna Airport, or Gaya Airport platform/terminal with personalized name boards, luggage help, and private cabs.',
        suggestedService: 'Pilgrimage Arrival Escort',
      },
      {
        id: 'trv_ghat_beach',
        label: 'What is Beach / River Ghat Assistance?',
        response: 'Ground assistants provide safe guidance, seating, boat coordination, and dedicated priest meeting points at Phalgu River, Punpun River, and sacred bath ghats.',
        suggestedService: 'Sacred River Ghat Support',
      },
      {
        id: 'trv_local_ground',
        label: 'What does Local Ground Assistance include?',
        response: 'Dedicated local ground assistants assist with temple entry passes, queue management, shoe counter safety, samagri sourcing, and local vehicle movement.',
        suggestedService: 'Local Ground Escort',
      },
      {
        id: 'trv_stay',
        label: 'What Accommodation arrangements are guided?',
        response: 'We guide you to clean, elder-friendly AC hotels and traditional dharamshalas located near Vishnupad Temple with elevator access and pure vegetarian dining.',
        suggestedService: 'Elder-Friendly Hotel Accommodation',
        requiresLeadCollection: true,
      },
      {
        id: 'trv_elder_eyes',
        label: 'What Elder Assistance and Eyes Support is available?',
        response: 'Specialized 1-on-1 ground support for senior citizens and visually or physically challenged pilgrims, ensuring safe navigation, wheelchair assistance, and gentle temple darshan.',
        suggestedService: 'Senior Citizen Travel Escort',
        requiresLeadCollection: true,
      },
      {
        id: 'trv_journey_plan',
        label: 'How to do Pilgrimage Journey Planning?',
        response: 'Our team prepares a step-by-step yatra schedule matching your train/flight arrival, sacred tithi timings, pandit appointments, and return transfers.',
        suggestedService: 'Yatra Itinerary Planning',
      },
      {
        id: 'trv_tracking',
        label: 'How do I Track my travel escort or driver?',
        response: 'Your Universal Reference ID (CHC-2026-XXXXXX) links directly to your assigned escort phone number, cab vehicle details, and live status on the Universal Tracking Engine.',
        suggestedService: 'Universal Pilgrimage Tracking',
      },
    ],
    fallbackResponse: 'I will forward your travel and accommodation query to our local pilgrimage coordination desk.',
  },
  'vahi-records': {
    categoryId: 'vahi-records',
    title: 'Vahi Lineage & Ledger AI',
    greeting: 'Namaste! Looking to understand Vahi meanings, search family records, or verify historic lineage ledgers in Gaya Ji?',
    initialPrompts: [
      {
        id: 'vahi_meaning',
        label: 'What is the Meaning of traditional Vahi records?',
        response: 'Vahi (Bahi) records are centuries-old handwritten genealogical ledgers preserved by traditional Gaya Pandas (Teerth Purohits), recording family names, Gotra, village origins, and ancestral pilgrimage visits.',
        suggestedService: 'Vahi Lineage History',
      },
      {
        id: 'vahi_search',
        label: 'How does Record Search work for ancestral ledgers?',
        response: 'By providing your ancestor name, native village, district, state, and Gotra, our team coordinates with authentic ledger custodians in Gaya Ji to locate your family’s historic ledger page.',
        suggestedService: 'Vahi Lineage Search Inquiry',
        requiresLeadCollection: true,
      },
      {
        id: 'vahi_verification',
        label: 'How is Lineage Verification conducted?',
        response: 'Authorized ledger custodians inspect original copperplate inscriptions and paper Vahis, verifying handwriting, signatures, and seals of past family patriarchs.',
        suggestedService: 'Lineage Verification Certificate',
      },
      {
        id: 'vahi_historic_entries',
        label: 'Can I view Historic Family Entries from past generations?',
        response: 'Yes! Digital high-resolution copies or transcribed extracts of your family’s historic ledger entries can be requested after identity verification.',
        suggestedService: 'Historic Ledger Extraction',
      },
      {
        id: 'vahi_updates',
        label: 'How to register Record Updates after a new ritual?',
        response: 'Upon completing Pind Daan or Shraddh, the presiding Panda enters the current pilgrim’s name, date, gotra, and signatures into the family Vahi ledger for future generations.',
        suggestedService: 'Vahi Ledger Registration Update',
      },
    ],
    fallbackResponse: 'I will submit your lineage query to an authorized Vahi ledger custodian for manual verification.',
  },
  'religious-partners': {
    categoryId: 'religious-partners',
    title: 'Religious Partner Network AI',
    greeting: 'Namaste! Are you a Pandit Ji, Purohit, Acharya, or traditional Gaya Panda seeking to join our network?',
    initialPrompts: [
      {
        id: 'rpn_eligibility',
        label: 'What are the Eligibility criteria to register as a partner?',
        response: 'Applicants must possess verified Vaidik education (Gurukul/University degree or hereditary Panda lineage), clean background credentials, and adhere to our ethical conduct code.',
        suggestedService: 'Religious Partner Registration',
      },
      {
        id: 'rpn_registration',
        label: 'How does the Partner Registration process work?',
        response: 'Submit your online registration form with basic details, select your specialization (Puja, Gaya Rituals, Vahi Ledger, Travel), and upload verification credentials.',
        suggestedService: 'Religious Partner Registration Form',
        requiresLeadCollection: true,
      },
      {
        id: 'rpn_documents',
        label: 'What Required Documents must be submitted?',
        response: 'Upload valid photo ID (Aadhaar/Passport), address proof, traditional lineage certificate or Gurukul Sanad, and passport-size photographs.',
        suggestedService: 'Partner Document Verification',
      },
      {
        id: 'rpn_approval',
        label: 'How does Verification & Approval work?',
        response: 'Our credential verification panel reviews your submitted documents, conducts a background/reference check, and completes video or in-person verification within 3 to 5 business days.',
        suggestedService: 'Partner Verification Desk',
      },
      {
        id: 'rpn_tracking',
        label: 'How to do Registration ID Tracking for applications?',
        response: 'Use your Partner Registration ID (e.g. CHC-2026-XXXXXX) on the Universal Tracking Engine to monitor real-time onboarding status from submission to approval.',
        suggestedService: 'Universal Partner Tracking',
      },
      {
        id: 'rpn_complaints',
        label: 'How are Complaints or quality issues handled?',
        response: 'Partner grievances or customer service feedback are reviewed directly by our Quality & Grievance Desk under strict transparency guidelines.',
        suggestedService: 'Partner Grievance Desk',
      },
      {
        id: 'rpn_support',
        label: 'What Partner Support services are provided?',
        response: 'Approved partners receive dedicated dispatch assistance, ritual samagri coordination, technology training, live stream support, and timely Dakshina settlement.',
        suggestedService: 'Partner Support Helpdesk',
      },
    ],
    fallbackResponse: 'I will submit your registration request to the partner onboarding committee for credential evaluation.',
  },
  booking: {
    categoryId: 'booking',
    title: 'Booking & Dakshina Quote AI',
    greeting: 'Namaste! I am your Booking Assistant. How can I assist with your ritual or pilgrimage booking?',
    initialPrompts: [
      {
        id: 'bk_quote',
        label: 'How are Dakshina & transparent quotes calculated?',
        response: 'All Dakshina quotes are structured transparently with upfront pricing, itemized Samagri breakdown, and priest honorarium. No hidden charges or extortion.',
        suggestedService: 'Service Catalog Quote',
      },
      {
        id: 'bk_confirm',
        label: 'How do I confirm my ritual booking date?',
        response: 'Submit your requested date, Gotra, and participant count. Our operations desk verifies Acharya availability and issues a formal URMS booking reference.',
        suggestedService: 'Direct Service Booking',
        requiresLeadCollection: true,
      },
    ],
    fallbackResponse: 'I will refer your booking request to our reservations team for custom confirmation.',
  },
  inquiry: {
    categoryId: 'inquiry',
    title: 'Service & Custom Inquiry AI',
    greeting: 'Namaste! Have a question about custom ritual requirements, dates, or family arrangements?',
    initialPrompts: [
      {
        id: 'inq_custom',
        label: 'Can I request a custom ritual or family package?',
        response: 'Yes! We accommodate custom family traditions, specific Vedic sampradayas, and multi-day ceremonies tailored to your family requirements.',
        suggestedService: 'Custom Ritual Inquiry',
        requiresLeadCollection: true,
      },
      {
        id: 'inq_turnaround',
        label: 'How fast do coordinators respond to inquiries?',
        response: 'Inquiries are assigned within 2-4 business hours, and an authorized coordinator will connect via WhatsApp or phone call.',
        suggestedService: 'General Inquiry Desk',
      },
    ],
    fallbackResponse: 'Your custom inquiry will be routed to a dedicated service coordinator for personalized assistance.',
  },
  tracking: {
    categoryId: 'tracking',
    title: 'Universal Reference Tracking AI',
    greeting: 'Namaste! Looking to track your service request or verify your Universal Reference ID?',
    initialPrompts: [
      {
        id: 'trk_format',
        label: 'What is a Universal Reference ID?',
        response: 'Every inquiry, booking, or partner registration generates a unique reference ID in the format CHC-YYYY-XXXXXX (e.g. CHC-2026-000123) for real-time customer tracking.',
        suggestedService: 'URMS Tracking Portal',
      },
      {
        id: 'trk_lookup',
        label: 'How can I check live service progress?',
        response: 'Type your reference ID (e.g. CHC-2026-000123) into the box below or visit /tracking to view current stage, assigned team, and next expected updates.',
        suggestedService: 'Universal Tracking Portal',
      },
    ],
    fallbackResponse: 'Please provide your reference ID (CHC-YYYY-XXXXXX) to retrieve live tracking status.',
  },
  complaint: {
    categoryId: 'complaint',
    title: 'Quality & Service Complaint AI',
    greeting: 'Namaste. We hold service quality to strict standards. How can we resolve your issue?',
    initialPrompts: [
      {
        id: 'cmp_report',
        label: 'How do I report a service quality issue?',
        response: 'We take quality feedback seriously. Submit your reference ID and issue details for priority audit by our quality assurance desk.',
        suggestedService: 'Quality Assurance Review',
        requiresLeadCollection: true,
      },
      {
        id: 'cmp_escalate',
        label: 'What is the resolution timeline for complaints?',
        response: 'Quality complaints are logged in URMS with HIGH priority and reviewed within 12 hours by our operations lead.',
        suggestedService: 'Operations Escalation Desk',
      },
    ],
    fallbackResponse: 'Your complaint will be logged into URMS with high priority for immediate operations review.',
  },
  grievance: {
    categoryId: 'grievance',
    title: 'Formal Grievance Redressal AI',
    greeting: 'Namaste. We are committed to transparency and ethical governance. Please state your grievance.',
    initialPrompts: [
      {
        id: 'grv_formal',
        label: 'How is a formal grievance processed?',
        response: 'Formal grievances are registered directly with the Governance Committee and tracked strictly under URMS audit rules until resolution.',
        suggestedService: 'Formal Grievance Desk',
        requiresLeadCollection: true,
      },
    ],
    fallbackResponse: 'Your formal grievance will be escalated directly to the Governance Redressal Officer.',
  },
  'founder-support': {
    categoryId: 'founder-support',
    title: 'Founder Desk & Priority AI',
    greeting: 'Namaste! Founder Support handles high-priority escalations, strategic inquiries, and executive assistance.',
    initialPrompts: [
      {
        id: 'fnd_priority',
        label: 'When should I contact Founder Support?',
        response: 'Founder Support is reserved for NRI emergency travel arrangements, complex inter-state family disputes, or unresolved high-priority requests.',
        suggestedService: 'Founder Desk Request',
        requiresLeadCollection: true,
      },
    ],
    fallbackResponse: 'Your request will be submitted directly to the Founder Support Desk for priority review.',
  },
  'company-info': {
    categoryId: 'company-info',
    title: 'Company Governance & Info AI',
    greeting: 'Namaste! Welcome to Connect Hub Co. How may I assist you with company details, policies, or guidance?',
    initialPrompts: [
      {
        id: 'co_about',
        label: 'What is Connect Hub Co.?',
        response: 'Connect Hub Co. is a sacred religious service and pilgrimage travel company dedicated to authentic Vedic traditions, verified lineage records, and transparent pilgrim assistance.',
        suggestedService: 'Company Overview',
      },
      {
        id: 'co_privacy',
        label: 'How are family lineage records protected?',
        response: 'We enforce strict confidentiality for ancestral Vahi records. Access is restricted to lineaged Pandas and verified family members under privacy governance.',
        suggestedService: 'Privacy & Data Governance',
      },
    ],
    fallbackResponse: 'I will direct your inquiry to our central customer relations team.',
  },
};
