export const ROUTES = {
  HOME: '/',
  PITRU_MOKSHA_GAYA: '/pitru-moksha-gaya',
  PITRU_MOKSHA_GAYA_ONLINE: '/pitru-moksha-gaya/online',
  PITRU_MOKSHA_GAYA_OFFLINE: '/pitru-moksha-gaya/offline',
  RITUAL_SERVICES: '/ritual-services',
  RITUAL_SERVICES_ONLINE: '/ritual-services/online',
  RITUAL_SERVICES_OFFLINE: '/ritual-services/offline',
  TRAVEL_ASSISTANCE: '/travel-assistance',
  VAHI_RECORDS: '/vahi-records',
  RELIGIOUS_PARTNERS: '/religious-partners',
  KNOWLEDGE_CENTER: '/knowledge-center',
  ASK_GENZ_AI: '/zen-g',
  BOOKING: '/services',
  INQUIRY: '/contact',
  TRACKING: '/tracking',
  COMPLAINT: '/complaint',
  GRIEVANCE: '/grievance',
  FOUNDER_SUPPORT: '/founder-support',
  POLICIES_LEGAL_TERMS: '/policies-and-legal-terms',
  REFUND_POLICY: '/refund-policy',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS: '/terms',
  BOOKING_TERMS: '/booking-terms',
  CANCELLATION_POLICY: '/cancellation-policy',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  WHATSAPP: '/contact?channel=whatsapp',
} as const;

export type RouteKey = keyof typeof ROUTES;
