"use client";
import { useEffect, useState } from "react";
import { getPartners } from "@/services/partner.api";
import { getPitruMokshaRequests, processPitruMokshaRequest } from "@/services/pitru-moksha.api";
import { PitruMokshaRequest } from "@/types/pitru-moksha";
import { ReligiousPartner } from "@/types/partner";
import { BookingStatus } from "@/types/booking";

const transitions: Record<BookingStatus, BookingStatus[]> = { PENDING: ["PENDING", "CONFIRMED", "CANCELLED"], CONFIRMED: ["CONFIRMED", "COMPLETED", "CANCELLED"], COMPLETED: ["COMPLETED"], CANCELLED: ["CANCELLED"] };

export default function PitruMokshaRequestsPage() {
  const [requests, setRequests] = useState<PitruMokshaRequest[]>([]); const [partners, setPartners] = useState<ReligiousPartner[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState<string | null>(null);
  async function load() { const [requestRows, partnerRows] = await Promise.all([getPitruMokshaRequests(), getPartners()]); setRequests(requestRows); setPartners(partnerRows.filter((partner) => partner.active)); }
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load requests.")); }, []);
  async function process(request: PitruMokshaRequest, data: { religiousPartnerId?: string; status?: BookingStatus; scheduledAt?: string }) { setSaving(request.id); setError(null); try { await processPitruMokshaRequest(request.id, data); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update request."); } finally { setSaving(null); } }
  return <main className="min-h-screen bg-gray-100 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">PitruMoksha Requests</h1><p className="mt-2 text-gray-600">Private customer intake and ritual coordination.</p>{error ? <p className="mt-4 rounded bg-red-50 p-3 text-red-700" role="alert">{error}</p> : null}<div className="mt-7 grid gap-6">{requests.map((request) => <article key={request.id} className="rounded-2xl bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{request.customerName}</h2><p className="text-sm text-gray-500">Submitted {new Date(request.createdAt).toLocaleString()} · {request.isNRI ? "NRI" : "India"}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold">{request.status}</span></div>
    <div className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><b>Contact</b><p>{request.phone}<br />{request.email ?? "No email"}<br />{request.city ? `${request.city}, ` : ""}{request.country}<br />Prefers {request.contactPreference}</p></div><div><b>Ritual</b><p>{request.serviceName}<br />Preferred {new Date(request.scheduledAt).toLocaleDateString()}<br />{request.pilgrimCount} pilgrim(s)</p></div><div><b>Ancestors</b><p className="whitespace-pre-wrap">{request.ancestorNames}<br />{request.gotra ? `Gotra: ${request.gotra}` : "Gotra not provided"}</p></div><div><b>Travel support</b><p>{request.travelSupport ? "Local travel requested" : "Not requested"}<br />{request.accommodationSupport ? "Accommodation requested" : "Not requested"}<br />{request.arrivalDetails ?? "No arrival details"}</p></div><div className="sm:col-span-2"><b>Special requirements</b><p className="whitespace-pre-wrap">{request.specialRequirements ?? "None"}</p></div></div>
    <div className="mt-6 grid gap-3 border-t pt-5 sm:grid-cols-3"><label>Religious partner<select className="mt-1 block w-full rounded border p-2" value={request.religiousPartnerId ?? ""} disabled={saving === request.id || request.status === "COMPLETED" || request.status === "CANCELLED"} onChange={(event) => void process(request, { religiousPartnerId: event.target.value })}><option value="">Unassigned</option>{partners.map((partner) => <option key={partner.id} value={partner.id}>{partner.name}</option>)}</select></label><label>Ritual date<input className="mt-1 block w-full rounded border p-2" type="date" value={request.scheduledAt.slice(0, 10)} disabled={saving === request.id || request.status === "COMPLETED" || request.status === "CANCELLED"} onChange={(event) => void process(request, { scheduledAt: `${event.target.value}T09:00:00.000Z` })} /></label><label>Status<select className="mt-1 block w-full rounded border p-2" value={request.status} disabled={saving === request.id} onChange={(event) => void process(request, { status: event.target.value as BookingStatus })}>{transitions[request.status].map((status) => <option key={status}>{status}</option>)}</select></label></div>
  </article>)}{!requests.length && !error ? <p className="rounded bg-white p-8 text-center text-gray-500">No PitruMoksha requests yet.</p> : null}</div></div></main>;
}
