import type { Metadata } from "next";
import Link from "next/link";
import { EnquiryForm } from "@/components/pitru-moksha/EnquiryForm";

export const metadata: Metadata = { title: "Pitru Moksha & Pind Daan in Gaya | Connect Hub Co", description: "Plan a respectful Pind Daan and Pitru Moksha seva in Gaya with verified religious partners, NRI coordination, and travel support.", keywords: ["Pind Daan Gaya", "Pitru Moksha Gaya", "Gaya pilgrimage", "NRI Pind Daan"] };
const packages = [{ name: "Essential Pind Daan", text: "Guided essential rites with a qualified religious partner." }, { name: "Complete Pitru Moksha Seva", text: "End-to-end ritual coordination based on family requirements." }, { name: "Family & NRI Assisted", text: "Extra planning for overseas families, travel and accommodation." }];

export default function PitruMokshaPage() { return <main className="bg-[#fffaf0] text-stone-800"><section className="bg-gradient-to-br from-orange-950 via-orange-800 to-amber-600 px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="font-semibold tracking-widest text-amber-200">PITRUMOKSHA GAYA</p><h1 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">Honour your ancestors with a thoughtfully coordinated seva in Gaya</h1><p className="mt-6 max-w-2xl text-lg text-orange-50">Clear guidance, verified religious partners and personal support for families in India and abroad.</p><Link href="#enquiry" className="mt-8 inline-block rounded-full bg-white px-7 py-3 font-semibold text-orange-900">Plan your seva</Link></div></section>
  <section className="mx-auto max-w-6xl px-6 py-16"><h2 className="text-center text-3xl font-bold">A respectful, supported pilgrimage</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{["Verified partner coordination", "Private family information", "NRI and travel assistance"].map((item) => <div key={item} className="rounded-2xl border border-amber-100 bg-white p-6 shadow-sm"><h3 className="font-semibold">{item}</h3><p className="mt-2 text-sm text-stone-600">Our team confirms requirements personally before the ritual plan is finalized.</p></div>)}</div></section>
  <section className="bg-white px-6 py-16"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-bold">Choose the support you need</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{packages.map((item) => <article key={item.name} className="rounded-2xl border border-orange-100 p-7"><h3 className="text-xl font-bold text-orange-900">{item.name}</h3><p className="mt-3 text-stone-600">{item.text}</p></article>)}</div></div></section>
  <section className="px-6 py-16"><EnquiryForm /></section><footer className="bg-stone-950 px-6 py-10 text-center text-sm text-stone-300">Connect Hub Co · Personal coordination for sacred services in Gaya</footer></main>; }
